import {
    ElAlert,
    ElAside,
    ElAvatar,
    ElBadge,
    ElButton,
    ElCard,
    ElCarousel,
    ElCarouselItem,
    ElCheckbox,
    ElCheckboxGroup,
    ElCol,
    ElCollapse,
    ElCollapseItem,
    ElCollapseTransition,
    ElContainer,
    ElDatePicker,
    ElDialog,
    ElDivider,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElEmpty,
    ElForm,
    ElFormItem,
    ElHeader,
    ElIcon,
    ElImage,
    ElInput,
    ElInputNumber,
    ElLoading,
    ElMain,
    ElMenu,
    ElMenuItem,
    ElOption,
    ElProgress,
    ElRadioButton,
    ElRadioGroup,
    ElRow,
    ElSelect,
    ElTable,
    ElTableColumn,
    ElTag,
    ElTimePicker,
    ElUpload,
} from 'element-plus'

const components = [
    ElAlert,
    ElAside,
    ElAvatar,
    ElBadge,
    ElButton,
    ElCard,
    ElCarousel,
    ElCarouselItem,
    ElCheckbox,
    ElCheckboxGroup,
    ElCol,
    ElCollapse,
    ElCollapseItem,
    ElCollapseTransition,
    ElContainer,
    ElDatePicker,
    ElDialog,
    ElDivider,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElEmpty,
    ElForm,
    ElFormItem,
    ElHeader,
    ElIcon,
    ElImage,
    ElInput,
    ElInputNumber,
    ElMain,
    ElMenu,
    ElMenuItem,
    ElOption,
    ElProgress,
    ElRadioButton,
    ElRadioGroup,
    ElRow,
    ElSelect,
    ElTable,
    ElTableColumn,
    ElTag,
    ElTimePicker,
    ElUpload,
]

export const installElement = (app) => {
    components.forEach((component) => {
        if (!component?.name) return
        app.component(component.name, component)
    })

    if (ElLoading?.directive) {
        app.directive('loading', ElLoading.directive)
    }
}

